// <auto-generated />
using System;
using BrooklynPark.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Brooklyn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250714080746_Fixed")]
    partial class Fixed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Brooklyn.Models.DowntimeLog", b =>
                {
                    b.Property<long>("DowntimeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DowntimeLogId"), 1L, 1);

                    b.Property<string>("DowntimeReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DowntimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("DowntimeLogId");

                    b.HasIndex("UserId");

                    b.ToTable("DowntimeLogs");
                });

            modelBuilder.Entity("Brooklyn.Models.DowntimeReason", b =>
                {
                    b.Property<long>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReasonId"), 1L, 1);

                    b.Property<long>("DowntimeTypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReasonId");

                    b.HasIndex("DowntimeTypeID");

                    b.ToTable("DowntimeReasons");
                });

            modelBuilder.Entity("Brooklyn.Models.DowntimeType", b =>
                {
                    b.Property<long>("DowntimeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DowntimeTypeId"), 1L, 1);

                    b.Property<string>("DownTimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DowntimeTypeId");

                    b.ToTable("DowntimeTypes");
                });

            modelBuilder.Entity("Brooklyn.Models.MachineInformation", b =>
                {
                    b.Property<long>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MachineId"), 1L, 1);

                    b.Property<long?>("ModelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkAreaId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("MachineId");

                    b.HasIndex("ModelId");

                    b.HasIndex("StationId");

                    b.HasIndex("WorkAreaId");

                    b.ToTable("MachineInformation");
                });

            modelBuilder.Entity("Brooklyn.Models.Model", b =>
                {
                    b.Property<long?>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("ModelId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Brooklyn.Models.QualityLog", b =>
                {
                    b.Property<long?>("QualityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("QualityLogId"), 1L, 1);

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualityStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("QualityLogId");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId");

                    b.ToTable("QualityLogs");
                });

            modelBuilder.Entity("Brooklyn.Models.Shift", b =>
                {
                    b.Property<long>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShiftId"), 1L, 1);

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Brooklyn.Models.StandardCycleTime", b =>
                {
                    b.Property<long>("StandardCycleTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StandardCycleTimeId"), 1L, 1);

                    b.Property<int?>("CycleTimeMinutes")
                        .HasColumnType("int");

                    b.Property<long?>("ModelId")
                        .HasColumnType("bigint");

                    b.HasKey("StandardCycleTimeId");

                    b.HasIndex("ModelId");

                    b.ToTable("StandardCycleTimes");
                });

            modelBuilder.Entity("Brooklyn.Models.Station", b =>
                {
                    b.Property<long>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StationId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Brooklyn.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Brooklyn.Models.WorkArea", b =>
                {
                    b.Property<long>("WorkAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkAreaId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkAreaId");

                    b.ToTable("WorkAreas");
                });

            modelBuilder.Entity("Brooklyn.Models.DowntimeLog", b =>
                {
                    b.HasOne("Brooklyn.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Brooklyn.Models.DowntimeReason", b =>
                {
                    b.HasOne("Brooklyn.Models.DowntimeType", "DowntimeType")
                        .WithMany("Reason")
                        .HasForeignKey("DowntimeTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DowntimeType");
                });

            modelBuilder.Entity("Brooklyn.Models.MachineInformation", b =>
                {
                    b.HasOne("Brooklyn.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");

                    b.HasOne("Brooklyn.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.HasOne("Brooklyn.Models.WorkArea", "WorkArea")
                        .WithMany()
                        .HasForeignKey("WorkAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Station");

                    b.Navigation("WorkArea");
                });

            modelBuilder.Entity("Brooklyn.Models.QualityLog", b =>
                {
                    b.HasOne("Brooklyn.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");

                    b.HasOne("Brooklyn.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Model");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Brooklyn.Models.StandardCycleTime", b =>
                {
                    b.HasOne("Brooklyn.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Brooklyn.Models.DowntimeType", b =>
                {
                    b.Navigation("Reason");
                });
#pragma warning restore 612, 618
        }
    }
}
